[package]
name = "rart-macros"
version = "0.0.0"
edition = "2021"
authors = ["Matheus T. dos Santos <tenoriomatheus0@gmail.com>"]

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
